


CREATE DATABASE T_Psales;
USE T_Psales;

-- CRIAR TABELA DE CURSOS
CREATE TABLE CURSOS
(
 -- PK, FK, TIPO DE DADOS

 IdCurso INT PRIMARY KEY IDENTITY

 ,Nome VARCHAR(200) NOT NULL UNIQUE

);

--CRIAR TABELA DE DISCIPLINAS

CREATE TABLE DISCIPLINAS
(
IdDisciplina INT PRIMARY KEY IDENTITY
,Nome VARCHAR(250)
,IdCurso INT FOREIGN KEY REFERENCES CURSOS(IdCurso) 
);

CREATE TABLE ALUNOS
(
IdAlunos INT PRIMARY KEY IDENTITY
,nome VARCHAR (200) NOT NULL UNIQUE
);

-- TABELA INTERMEDIÁRIA

CREATE TABLE ALUNOSCURSOS
(
IdCurso INT FOREIGN KEY REFERENCES CURSOS (IdCurso)
,IdAlunos INT FOREIGN KEY REFERENCES ALUNOS(IdAlunos)
);


INSERT INTO CURSOS(Nome) VALUES('Tec em dev de sistemas');
INSERT INTO CURSOS VALUES('Tec em redes');

SELECT *
FROM CURSOS;

SELECT *
FROM CURSOS 
WHERE IdCurso = 4;

--ATT

UPDATE CURSOS
SET Nome = 'tECNICO EM DEV DE SISTEMAS'
WHERE IdCurso = 1;




SELECT * 
 FROM DISCIPLINAS;

 INSERT INTO DISCIPLINAS(Nome, IdCurso)
VALUES                  ('HTML', 1 );

 SELECT * FROM CURSOS;

 --DELETE FROM CURSOS
 --WHERE IdCurso = 1;

