USE T_Empresa;

--DDL 

CREATE TABLE DEPARTAMENTO
(
IDDEPARTAMENTO INT PRIMARY KEY IDENTITY
,NOMEDEP VARCHAR (200) NOT NULL UNIQUE

);

CREATE TABLE HABILIDADE 
(
IDHABILIDADE INT PRIMARY KEY IDENTITY
,NOMEHAB VARCHAR(200) NOT NULL UNIQUE
);

CREATE TABLE FUNCIONARIO
(
IDFUNCIONARIO INT PRIMARY KEY IDENTITY
,NOMEFUN VARCHAR(200) NOT NULL UNIQUE
,SALARIO INT
,IDDEPARTAMENTO INT FOREIGN KEY REFERENCES DEPARTAMENTO(IDDEPARTAMENTO)

);

CREATE TABLE FUNCIONARIOHABILIDADE
(
IDFUNCIONARIO INT FOREIGN KEY REFERENCES FUNCIONARIO (IDFUNCIONARIO)
,IDHABILIDADE INT FOREIGN KEY REFERENCES HABILIDADE (IDHABILIDADE)
);

--FIM DDL
