USE T_SSTOP;

--CRIAR TABELA DE ESTILOS MUSICAIS 

CREATE TABLE ESTILOS
(
  IDESTILOS INT PRIMARY KEY IDENTITY
  ,NOME VARCHAR(200) NOT NULL UNIQUE
);



--CRIAR TABELA DE ARTISTAS

CREATE TABLE ARTISTAS
(
 IDARTISTA INT PRIMARY KEY IDENTITY
 ,NOME VARCHAR(200) NOT NULL UNIQUE
 ,IDESTILOS INT FOREIGN KEY REFERENCES ESTILOS(IDESTILOS)
);

SELECT *
FROM ARTISTAS;
SELECT*
FROM ESTILOS;


INSERT INTO ESTILOS(NOME) VALUES ('POP')
								,('')

--ARTISTAS (NOME, IDESTILOMUSICA)

--INSERT INTO DISCIPLINAS (NOME, IDCURSO)
INSERT INTO ARTISTAS(Nome, IDESTILOS)
VALUES                  ('Madonna', 1 );

INSERT INTO ARTISTAS (NOME, IDESTILOS)
VALUES  ('QUEEN', 2); 

UPDATE ESTILOS
SET NOME = 'POP'
WHERE IDESTILOS = 1;

UPDATE ESTILOS 
SET NOME = 'ROCK'
WHERE IDESTILOS = 2;

UPDATE ESTILOS
SET NOME = 'AXÉ'
WHERE IDESTILOS = 3;

UPDATE ARTISTAS
SET IDESTILOS = 1
WHERE IDARTISTA = 1;

UPDATE ARTISTAS
SET IDESTILOS = 2
WHERE IDARTISTA = 2;



            



