USE T_Moda;

--DDL

--CRIAÇÃO TABELAS

CREATE TABLE CAMISETA
(
IdCamiseta INT PRIMARY KEY IDENTITY
,Camiseta VARCHAR (200) NOT NULL UNIQUE

);

CREATE TABLE MARCA
(
IdMarca INT PRIMARY KEY IDENTITY
,Marca VARCHAR (200) NOT NULL UNIQUE
);

CREATE TABLE COR
(
IdCor INT PRIMARY KEY IDENTITY
,COR VARCHAR (200) NOT NULL UNIQUE
);

CREATE TABLE TAMANHO 
(
IDTAMANHO INT PRIMARY KEY IDENTITY
,TAMANHO VARCHAR(200) NOT NULL UNIQUE
);

CREATE TABLE CCT
(
IdCamiseta INT FOREIGN KEY REFERENCES CAMISETA(IdCamiseta)
,IdCor INT FOREIGN KEY REFERENCES COR(IdCor)
,IDTAMANHO INT FOREIGN KEY REFERENCES TAMANHO(IDTAMANHO)
);

create table marcaroupa
(
Camiseta VARCHAR (200) FOREIGN KEY REFERENCES CAMISETA (Camiseta)
,Marca VARCHAR (200) FOREIGN KEY REFERENCES MARCA (Marca)
);


--FIM DDL



--DML

--INSERIR, DELETAR E ATUALIZAR INFO NAS TABELAS

INSERT INTO CAMISETA (Camiseta) VALUES ('CAMISA1'), ('CAMISA2'), ('CAMISA3');
INSERT INTO CAMISETA (Camiseta) VALUES ('CAMIS4'), ('CAMISA5');



INSERT INTO MARCA (Marca) VALUES ('NIKE'), ('ADIDAS'), ('LACOSTE');

INSERT INTO COR (COR) VALUES ('VERDE'), ('VERMELHO'), ('AZUL');

INSERT INTO TAMANHO (TAMANHO) VALUES ('PP'), ('P'), ('M'), ('G'), ('GG');

INSERT INTO CCT VALUES (1, 1, 1), (1, 2, 3), (2,3,2), (2,1,4), (3,3,4);

INSERT INTO marcaroupa VALUES ('CAMISA1', 'SUPREME'), ('CAMISA2', 'HERING');

UPDATE MARCA SET Marca = 'SUPREME' WHERE IdMarca = 2;
UPDATE MARCA SET Marca = 'HERING' WHERE IdMarca = 3;

--FIM DML


--DQL

--SELECIONAR

SELECT * FROM CAMISETA ORDER BY IdCamiseta ASC;

SELECT * FROM MARCA ORDER BY IdMarca ASC;

SELECT * FROM COR ORDER BY IdCor ASC;


ALTER TABLE CAMISETA
ADD IdMarca INT FOREIGN KEY REFERENCES MARCA(IdMarca)

select * 
from CAMISETA;

select * from CCT;

select * from marcaroupa;


