CREATE DATABASE T_Livros;

USE T_Livros;
-- DDL CRIAMOS TABELAS
-- CRIAR, ALTERAR E DELETAR
CREATE TABLE GENERO
(
  IDGENERO INT PRIMARY KEY IDENTITY
  ,NOME VARCHAR(200) NOT NULL UNIQUE
);

CREATE TABLE AUTOR
(
 IDAUTOR INT PRIMARY KEY IDENTITY
 ,NOME VARCHAR(200)  
 ,EMAIL VARCHAR(250) 
 ,ATIVO INT
 ,DATA DATE

);

CREATE TABLE LIVRO
(
 IDLIVRO INT PRIMARY KEY IDENTITY
 ,NOME VARCHAR(200) NOT NULL UNIQUE
 ,IDGENERO  INT FOREIGN KEY REFERENCES GENERO (IDGENERO)
 ,IDAUTOR INT FOREIGN KEY REFERENCES AUTOR (IDAUTOR)
);

--FIM DDL

--DML PREENCHEMOS TABELAS
-- INSERIR, DELETAR, ATUALIZAR

INSERT INTO GENERO VALUES ('ROMANCE'), ('AVENTURA'), ('FANTASIA');

INSERT INTO AUTOR (NOME, EMAIL) VALUES ('JANE AUSTEN', 'T@T.COM'), ('JAMES', 'J@J.COM'), ('ROWLING', 'D@D.COM');

--INSERT INTO LIVRO VALUES ('ORGULHO E PRECONCEITO', 1, 1), ('MAZE RUNNER', 2, 2), ('HARRY POTTER', 3, 3);




