USE T_SSSTOP;

-- CRIAR TABELA DE CURSOS
CREATE TABLE CURSO
(
 -- PK, FK, TIPO DE DADOS

 IdCurso INT PRIMARY KEY IDENTITY

 ,Nome VARCHAR(200) NOT NULL UNIQUE

);

--CRIAR TABELA DE DISCIPLINAS

CREATE TABLE DISCIPLINA
(
IdDisciplina INT PRIMARY KEY IDENTITY
,Nome VARCHAR(250)
,IdCurso INT FOREIGN KEY REFERENCES CURSO(IdCurso) 
);

CREATE TABLE ALUNO
(
IdAlunos INT PRIMARY KEY IDENTITY
,nome VARCHAR (200) NOT NULL UNIQUE
);

-- TABELA INTERMEDIÁRIA

CREATE TABLE ALUNOCURSOS
(
IdCurso INT FOREIGN KEY REFERENCES CURSO (IdCurso)
,IdAlunos INT FOREIGN KEY REFERENCES ALUNO(IdAlunos)
);

-- inserção
INSERT INTO Curso (Nome) VALUES ('Técnico Dev');
INSERT INTO Curso (Nome) VALUES ('Técnico Redes');
INSERT INTO Curso VALUES ('Curso A');
INSERT INTO Curso VALUES ('Curso B'), ('Curso C');

-- SELECIONAR TODOS OS CURSOS
SELECT IdCurso, Nome FROM Curso;
-- SELECT NOME_COLUNAS FROM TABELA
SELECT Nome, IdCurso FROM Curso;
SELECT Nome FROM Curso;
SELECT * FROM Curso;

-- INSERIR AS DISCIPLINAS
INSERT INTO Disciplina VALUES ('HTML', 1);
INSERT INTO Disciplina VALUES ('CSS', 1), ('Design', 1), ('Conceito de Redes', 2);

SELECT * FROM Disciplina;

INSERT INTO Aluno VALUES ('Tadeu'), ('Kevin');

SELECT * FROM Aluno;

INSERT INTO ALUNOCURSOS VALUES (1, 1), (2, 1);

SELECT * FROM ALUNOCURSOS;

SELECT *
FROM DISCIPLINA
FULL JOIN CURSO
ON DISCIPLINA.IdCurso = CURSO.IdCurso

SELECT *
FROM DISCIPLINA
FULL OUTER JOIN CURSO 
ON DISCIPLINA.Nome = CURSO.Nome






